spring.application.name=payflow

# Application

spring.main.banner-mode=off

# Profiles

spring.profiles.default=dev

# Actuator

management.endpoints.web.exposure.include=health,info

management.endpoint.health.show-details=never